openapi: 3.1.0
info:
  version: 1.0.0
  title: Water Tracker API docs
  description: |-
    This is a documentation of Water Tracker app.

    This project is free web-application for comfortable record keeping of drunk water.

    The main goal is to provide users with instruments for control and visualization of water consumption.

    There are possibilities of registration, authentication and authorization of users. They can calculate daily water volume depending on their gender, body weight and sport activities, add/edit/delete time and amount of water they drank. As well, there are list of records for today and month statistic of reaching daily volume goal.

    It is easy and convenient to use app with an intuitive interface, secured by hashing passwords and using access tokens.

tags:
  - name: User
    description: Operations with user.
  - name: Auth
    description: Auth operations.
  - name: Water
    description: Operations with water.
servers:
  - url: https://water-tracker-06.onrender.com
paths:
  /user:
    get:
      $ref: ../swagger/paths/user/get.yaml
    patch:
      $ref: ../swagger/paths/user/patch.yaml
  /user/avatar:
    patch:
      $ref: ../swagger/paths/user/avatar/patch.yaml
  /user/waterRate:
    patch:
      $ref: ../swagger/paths/user/waterRate/patch.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/post.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/post.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh/post.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/post.yaml
  /water:
    post:
      $ref: ../swagger/paths/water/post.yaml
  /water/{id}:
    patch:
      $ref: ../swagger/paths/water/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/water/{id}/delete.yaml
  /water/day:
    get:
      $ref: ../swagger/paths/water/day/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
